<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
    <PackageReference Include="NFluent" Version="3.1.0" />
    <PackageReference Include="OpenTelemetry" Version="1.15.3" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Addons\SimpleW.Service.BasicAuth\SimpleW.Service.BasicAuth.csproj" />
    <ProjectReference Include="..\Addons\SimpleW.Helper.BasicAuth\SimpleW.Helper.BasicAuth.csproj" />
    <ProjectReference Include="..\Addons\SimpleW.Helper.DependencyInjection\SimpleW.Helper.DependencyInjection.csproj" />
    <ProjectReference Include="..\Addons\SimpleW.Helper.Hosting\SimpleW.Helper.Hosting.csproj" />
    <ProjectReference Include="..\Addons\SimpleW.Service.Jwt\SimpleW.Service.Jwt.csproj" />
    <ProjectReference Include="..\Addons\SimpleW.Service.Background\SimpleW.Service.Background.csproj" />
    <ProjectReference Include="..\Addons\SimpleW.Service.Firewall\SimpleW.Service.Firewall.csproj" />
    <ProjectReference Include="..\Addons\SimpleW.Service.FileBrowser\SimpleW.Service.FileBrowser.csproj" />
    <ProjectReference Include="..\Addons\SimpleW.Helper.Jwt\SimpleW.Helper.Jwt.csproj" />
    <ProjectReference Include="..\Addons\SimpleW.JsonEngine.Newtonsoft\SimpleW.JsonEngine.Newtonsoft.csproj" />
    <ProjectReference Include="..\SimpleW\SimpleW.csproj" />
  </ItemGroup>

</Project>
