version: 40
jobs:
- name: CI
  steps:
  - !CheckoutStep
    name: checkout code
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    cloneDepth: 1
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: build SimpleW
    runInContainer: true
    image: docksdev/band:8.0
    interpreter: !DefaultInterpreter
      commands: |
        cd src/SimpleW/
        dotnet build -c @param:build_configuration@ SimpleW.csproj
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: build SimpleW.Newtonsoft
    runInContainer: true
    image: docksdev/band:8.0
    interpreter: !DefaultInterpreter
      commands: |
        cd src/SimpleW.Newtonsoft/
        dotnet build -c @param:build_configuration@ SimpleW.Newtonsoft.csproj
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - !PublishArtifactStep
    name: publish artifact SimpleW
    sourcePath: src/SimpleW/bin/@param:build_configuration@/
    artifacts: '*/SimpleW.dll'
    condition: SUCCESSFUL
    optional: false
  - !PublishArtifactStep
    name: publish artifact SimpleW.Newtonsoft
    sourcePath: src/SimpleW.Newtonsoft/bin/@param:build_configuration@/
    artifacts: '*/SimpleW.Newtonsoft.dll'
    condition: SUCCESSFUL
    optional: false
  paramSpecs:
  - !ChoiceParam
    name: build_configuration
    description: Build Configuration
    allowMultiple: false
    allowEmpty: false
    choiceProvider: !SpecifiedChoices
      choices:
      - value: Release
        color: '#0d87e9'
      - value: Debug
        color: '#0d87e9'
    defaultValueProvider: !SpecifiedDefaultValue
      value: Release
  triggers:
  - !BranchUpdateTrigger
    paths: src/SimpleW/ src/SimpleW.Newtonsoft/
    paramMatrix:
    - name: build_configuration
      secret: false
      valuesProvider: !SpecifiedValues
        values:
        - - Release
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: CD nuget
  steps:
  - !CheckoutStep
    name: checkout code
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    cloneDepth: 1
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: build SimpleW
    runInContainer: true
    image: docksdev/band:8.0
    interpreter: !DefaultInterpreter
      commands: |
        cd src/SimpleW
        dotnet pack -c Release SimpleW.csproj
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: build SimpleW.Newtonsoft
    runInContainer: true
    image: docksdev/band:8.0
    interpreter: !DefaultInterpreter
      commands: |
        cd src/SimpleW.Newtonsoft
        dotnet pack -c Release SimpleW.Newtonsoft.csproj
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - !PublishArtifactStep
    name: publish artifact SimpleW
    sourcePath: src/SimpleW/bin/Release/
    artifacts: '*.*nupkg'
    condition: SUCCESSFUL
    optional: false
  - !PublishArtifactStep
    name: publish artifact SimpleW.Newtonsoft
    sourcePath: src/SimpleW.Newtonsoft/bin/Release/
    artifacts: '*.*nupkg'
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: deploy SimpleW to nuget.org
    runInContainer: true
    image: docksdev/band:8.0
    interpreter: !DefaultInterpreter
      commands: |
        cd src/SimpleW/bin/Release
        dotnet nuget push *.nupkg --api-key @secret:nuget_token@ --source https://api.nuget.org/v3/index.json
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: deploy SimpleW.Newtonsoft to nuget.org
    runInContainer: true
    image: docksdev/band:8.0
    interpreter: !DefaultInterpreter
      commands: |
        cd src/SimpleW.Newtonsoft/bin/Release
        dotnet nuget push *.nupkg --api-key @secret:nuget_token@ --source https://api.nuget.org/v3/index.json
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  jobDependencies:
  - jobName: CI
    requireSuccessful: true
    paramMatrix:
    - name: build_configuration
      secret: false
      valuesProvider: !SpecifiedValues
        values:
        - - Release
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: CM github
  steps:
  - !PushRepository
    name: push
    remoteUrl: https://github.com/stratdev3/SimpleW
    passwordSecret: github_token
    force: true
    condition: SUCCESSFUL
    optional: false
  jobDependencies:
  - jobName: CI
    requireSuccessful: true
    paramMatrix:
    - name: build_configuration
      secret: false
      valuesProvider: !SpecifiedValues
        values:
        - - Release
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
