version: 43
jobs:
- name: CI
  steps:
  - type: CheckoutStep
    name: checkout code
    cloneCredential:
      type: DefaultCredential
    withLfs: false
    withSubmodules: false
    cloneDepth: 1
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: build SimpleW
    runInContainer: true
    image: mcr.microsoft.com/dotnet/sdk:10.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/SimpleW/
        dotnet build -c @param:build_configuration@ SimpleW.csproj
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: build SimpleW.JsonEngine.Newtonsoft
    runInContainer: true
    image: mcr.microsoft.com/dotnet/sdk:10.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/SimpleW.JsonEngine.Newtonsoft/
        dotnet build -c @param:build_configuration@ SimpleW.JsonEngine.Newtonsoft.csproj
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: build SimpleW.Helper.Hosting
    runInContainer: true
    image: mcr.microsoft.com/dotnet/sdk:10.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/SimpleW.Helper.Hosting/
        dotnet build -c @param:build_configuration@ SimpleW.Helper.Hosting.csproj
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: build SimpleW.Service.Firewall
    runInContainer: true
    image: mcr.microsoft.com/dotnet/sdk:10.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/SimpleW.Service.Firewall/
        dotnet build -c @param:build_configuration@ SimpleW.Service.Firewall.csproj
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: build SimpleW.Helper.Razor
    runInContainer: true
    image: mcr.microsoft.com/dotnet/sdk:10.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/SimpleW.Helper.Razor/
        dotnet build -c @param:build_configuration@ SimpleW.Helper.Razor.csproj
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: build SimpleW.Helper.Swagger
    runInContainer: true
    image: mcr.microsoft.com/dotnet/sdk:10.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/SimpleW.Helper.Swagger/
        dotnet build -c @param:build_configuration@ SimpleW.Helper.Swagger.csproj
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: build SimpleW.Service.Chaos
    runInContainer: true
    image: mcr.microsoft.com/dotnet/sdk:10.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/SimpleW.Service.Chaos/
        dotnet build -c @param:build_configuration@ SimpleW.Service.Chaos.csproj
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: build SimpleW.Service.Latency
    runInContainer: true
    image: mcr.microsoft.com/dotnet/sdk:10.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/SimpleW.Service.Latency/
        dotnet build -c @param:build_configuration@ SimpleW.Service.Latency.csproj
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: test
    runInContainer: true
    image: mcr.microsoft.com/dotnet/sdk:10.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/test/
        dotnet test
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: PublishArtifactStep
    name: publish artifact
    sourcePath: src/SimpleW/bin/@param:build_configuration@/
    artifacts: '*/SimpleW.dll'
    condition: SUCCESSFUL
    optional: false
  paramSpecs:
  - type: ChoiceParam
    name: build_configuration
    description: Build Configuration
    allowMultiple: false
    allowEmpty: false
    choiceProvider:
      type: SpecifiedChoices
      choices:
      - value: Release
        color: '#0d87e9'
      - value: Debug
        color: '#0d87e9'
    defaultValueProvider:
      type: SpecifiedDefaultValue
      value: Release
  triggers:
  - type: BranchUpdateTrigger
    paths: src/SimpleW/ src/test/
    userMatch: anyone
    paramMatrix:
    - valuesProvider:
        type: SpecifiedValues
        values:
        - - Release
      secret: false
      name: build_configuration
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: CD nuget
  steps:
  - type: CheckoutStep
    name: checkout code
    cloneCredential:
      type: DefaultCredential
    withLfs: false
    withSubmodules: false
    cloneDepth: 1
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: build SimpleW
    runInContainer: true
    image: mcr.microsoft.com/dotnet/sdk:10.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/SimpleW
        TS=$(date +"%Y%m%d")-@build_number@
        sed -i -E "s#<Version>([0-9]+\.[0-9]+\.[0-9]+-(alpha|beta|rc))</Version>#<Version>\\1.${TS}</Version>#g" SimpleW.csproj
        dotnet pack -c Release SimpleW.csproj
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: build SimpleW.JsonEngine.Newtonsoft
    runInContainer: true
    image: mcr.microsoft.com/dotnet/sdk:10.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/SimpleW.JsonEngine.Newtonsoft
        TS=$(date +"%Y%m%d")-@build_number@
        sed -i -E "s#<Version>([0-9]+\.[0-9]+\.[0-9]+-(alpha|beta|rc))</Version>#<Version>\\1.${TS}</Version>#g" SimpleW.JsonEngine.Newtonsoft.csproj
        dotnet pack -c Release SimpleW.JsonEngine.Newtonsoft.csproj
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: build SimpleW.Helper.Hosting
    runInContainer: true
    image: mcr.microsoft.com/dotnet/sdk:10.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/SimpleW.Helper.Hosting
        TS=$(date +"%Y%m%d")-@build_number@
        sed -i -E "s#<Version>([0-9]+\.[0-9]+\.[0-9]+-(alpha|beta|rc))</Version>#<Version>\\1.${TS}</Version>#g" SimpleW.Helper.Hosting.csproj
        dotnet pack -c Release SimpleW.Helper.Hosting.csproj
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: build SimpleW.Service.Firewall
    runInContainer: true
    image: mcr.microsoft.com/dotnet/sdk:10.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/SimpleW.Service.Firewall
        TS=$(date +"%Y%m%d")-@build_number@
        sed -i -E "s#<Version>([0-9]+\.[0-9]+\.[0-9]+-(alpha|beta|rc))</Version>#<Version>\\1.${TS}</Version>#g" SimpleW.Service.Firewall.csproj
        dotnet pack -c Release SimpleW.Service.Firewall.csproj
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: build SimpleW.Helper.Razor
    runInContainer: true
    image: mcr.microsoft.com/dotnet/sdk:10.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/SimpleW.Helper.Razor
        TS=$(date +"%Y%m%d")-@build_number@
        sed -i -E "s#<Version>([0-9]+\.[0-9]+\.[0-9]+-(alpha|beta|rc))</Version>#<Version>\\1.${TS}</Version>#g" SimpleW.Helper.Razor.csproj
        dotnet pack -c Release SimpleW.Helper.Razor.csproj
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: build SimpleW.Helper.Swagger
    runInContainer: true
    image: mcr.microsoft.com/dotnet/sdk:10.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/SimpleW.Helper.Swagger
        TS=$(date +"%Y%m%d")-@build_number@
        sed -i -E "s#<Version>([0-9]+\.[0-9]+\.[0-9]+-(alpha|beta|rc))</Version>#<Version>\\1.${TS}</Version>#g" SimpleW.Helper.Swagger.csproj
        dotnet pack -c Release SimpleW.Helper.Swagger.csproj
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: build SimpleW.Service.Chaos
    runInContainer: true
    image: mcr.microsoft.com/dotnet/sdk:10.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/SimpleW.Service.Chaos
        TS=$(date +"%Y%m%d")-@build_number@
        sed -i -E "s#<Version>([0-9]+\.[0-9]+\.[0-9]+-(alpha|beta|rc))</Version>#<Version>\\1.${TS}</Version>#g" SimpleW.Service.Chaos.csproj
        dotnet pack -c Release SimpleW.Service.Chaos.csproj
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: build SimpleW.Service.Latency
    runInContainer: true
    image: mcr.microsoft.com/dotnet/sdk:10.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/SimpleW.Service.Latency
        TS=$(date +"%Y%m%d")-@build_number@
        sed -i -E "s#<Version>([0-9]+\.[0-9]+\.[0-9]+-(alpha|beta|rc))</Version>#<Version>\\1.${TS}</Version>#g" SimpleW.Service.Latency.csproj
        dotnet pack -c Release SimpleW.Service.Latency.csproj
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: build SimpleW.Service.OpenID
    runInContainer: true
    image: mcr.microsoft.com/dotnet/sdk:10.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/SimpleW.Service.OpenID
        TS=$(date +"%Y%m%d")-@build_number@
        sed -i -E "s#<Version>([0-9]+\.[0-9]+\.[0-9]+-(alpha|beta|rc))</Version>#<Version>\\1.${TS}</Version>#g" SimpleW.Service.OpenID.csproj
        dotnet pack -c Release SimpleW.Service.OpenID.csproj
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: PublishArtifactStep
    name: publish artifact SimpleW
    sourcePath: src/SimpleW/bin/Release/
    artifacts: '*.*nupkg'
    condition: SUCCESSFUL
    optional: false
  - type: PublishArtifactStep
    name: publish artifact SimpleW.JsonEngine.Newtonsoft
    sourcePath: src/SimpleW.JsonEngine.Newtonsoft/bin/Release/
    artifacts: '*.*nupkg'
    condition: SUCCESSFUL
    optional: false
  - type: PublishArtifactStep
    name: publish artifact SimpleW.Helper.Hosting
    sourcePath: src/SimpleW.Helper.Hosting/bin/Release/
    artifacts: '*.*nupkg'
    condition: SUCCESSFUL
    optional: false
  - type: PublishArtifactStep
    name: publish artifact SimpleW.Service.Firewall
    sourcePath: src/SimpleW.Service.Firewall/bin/Release/
    artifacts: '*.*nupkg'
    condition: SUCCESSFUL
    optional: false
  - type: PublishArtifactStep
    name: publish artifact SimpleW.Helper.Razor
    sourcePath: src/SimpleW.Helper.Razor/bin/Release/
    artifacts: '*.*nupkg'
    condition: SUCCESSFUL
    optional: false
  - type: PublishArtifactStep
    name: publish artifact SimpleW.Helper.Swagger
    sourcePath: src/SimpleW.Helper.Swagger/bin/Release/
    artifacts: '*.*nupkg'
    condition: SUCCESSFUL
    optional: false
  - type: PublishArtifactStep
    name: publish artifact SimpleW.Service.Chaos
    sourcePath: src/SimpleW.Service.Chaos/bin/Release/
    artifacts: '*.*nupkg'
    condition: SUCCESSFUL
    optional: false
  - type: PublishArtifactStep
    name: publish artifact SimpleW.Service.Latency
    sourcePath: src/SimpleW.Service.Latency/bin/Release/
    artifacts: '*.*nupkg'
    condition: SUCCESSFUL
    optional: false
  - type: PublishArtifactStep
    name: publish artifact SimpleW.Service.OpenID
    sourcePath: src/SimpleW.Service.OpenID/bin/Release/
    artifacts: '*.*nupkg'
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: deploy SimpleW to nuget.org
    runInContainer: true
    image: docksdev/band:8.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/SimpleW/bin/Release
        dotnet nuget push *.nupkg --api-key @secret:nuget_token@ --source https://api.nuget.org/v3/index.json
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: deploy SimpleW.JsonEngine.Newtonsoft to nuget.org
    runInContainer: true
    image: docksdev/band:8.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/SimpleW.JsonEngine.Newtonsoft/bin/Release
        dotnet nuget push *.nupkg --api-key @secret:nuget_token@ --source https://api.nuget.org/v3/index.json
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: deploy SimpleW.Helper.Hosting to nuget.org
    runInContainer: true
    image: docksdev/band:8.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/SimpleW.Helper.Hosting/bin/Release
        dotnet nuget push *.nupkg --api-key @secret:nuget_token@ --source https://api.nuget.org/v3/index.json
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: deploy SimpleW.Service.Firewall to nuget.org
    runInContainer: true
    image: docksdev/band:8.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/SimpleW.Service.Firewall/bin/Release
        dotnet nuget push *.nupkg --api-key @secret:nuget_token@ --source https://api.nuget.org/v3/index.json
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: deploy SimpleW.Helper.Razor to nuget.org
    runInContainer: true
    image: docksdev/band:8.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/SimpleW.Helper.Razor/bin/Release
        dotnet nuget push *.nupkg --api-key @secret:nuget_token@ --source https://api.nuget.org/v3/index.json
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: deploy SimpleW.Service.Chaos to nuget.org
    runInContainer: true
    image: docksdev/band:8.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/SimpleW.Service.Chaos/bin/Release
        dotnet nuget push *.nupkg --api-key @secret:nuget_token@ --source https://api.nuget.org/v3/index.json
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: deploy SimpleW.Helper.Swagger to nuget.org
    runInContainer: true
    image: docksdev/band:8.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/SimpleW.Helper.Swagger/bin/Release
        dotnet nuget push *.nupkg --api-key @secret:nuget_token@ --source https://api.nuget.org/v3/index.json
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: deploy SimpleW.Service.Latency to nuget.org
    runInContainer: true
    image: docksdev/band:8.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/SimpleW.Service.Latency/bin/Release
        dotnet nuget push *.nupkg --api-key @secret:nuget_token@ --source https://api.nuget.org/v3/index.json
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: deploy SimpleW.Service.OpenID to nuget.org
    runInContainer: true
    image: docksdev/band:8.0
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd src/SimpleW.Service.OpenID/bin/Release
        dotnet nuget push *.nupkg --api-key @secret:nuget_token@ --source https://api.nuget.org/v3/index.json
    useTTY: false
    condition: SUCCESSFUL
    optional: false
  jobDependencies:
  - jobName: CI
    requireSuccessful: true
    paramMatrix:
    - valuesProvider:
        type: SpecifiedValues
        values:
        - - Release
      secret: false
      name: build_configuration
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: CM github
  steps:
  - type: PushRepository
    name: push
    remoteUrl: https://github.com/stratdev3/SimpleW
    passwordSecret: github_token
    force: true
    condition: SUCCESSFUL
    optional: false
  jobDependencies:
  - jobName: CI
    requireSuccessful: true
    paramMatrix:
    - valuesProvider:
        type: SpecifiedValues
        values:
        - - Release
      secret: false
      name: build_configuration
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
