name: Build Linux

on:
  push:
    branches:
      - master
      - testing
    paths:
      - 'src/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Setup dotnet"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x.x

      - name: "Build SimpleW"
        run: |
          cd src/SimpleW
          dotnet restore
          dotnet build --configuration Release
          # dotnet test

      - name: "Build SimpleW.Newtonsoft"
        run: |
          cd src/SimpleW.Newtonsoft
          dotnet restore
          dotnet build --configuration Release
          # dotnet test
