name: MacOS

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Setup dotnet"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x.x

      - name: "Build"
        run: |
          cd src/SimpleW
          dotnet restore
          dotnet build --configuration Release
          # dotnet test
